Default: &defaults
  database: first-yesod-app.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: first-yesod-app_test.sqlite3
  <<: *defaults

Staging:
  database: first-yesod-app_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: first-yesod-app_production.sqlite3
  poolsize: 100
  <<: *defaults
